import React, { useState } from 'react';
import { Camera, Loader2 } from 'lucide-react';
import DashboardLayout from '../components/Layout/DashboardLayout';
import Button from '../components/UI/Button';
import { useAuth } from '../context/AuthContext';
import api from '../api/axios';

export default function Profile() {
  const { user, updateUser } = useAuth();
  const [form, setForm] = useState({ nama: user?.nama || '', username: user?.username || '', email: user?.email || '', deskripsi: user?.deskripsi || '', foto_url: user?.foto_url || '' });
  const [saving, setSaving] = useState(false); const [uploading, setUploading] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const set = (key, value) => setForm((valueBefore) => ({ ...valueBefore, [key]: value }));
  const upload = async (event) => { const file = event.target.files?.[0]; if (!file) return; setUploading(true); setError(''); try { const body = new FormData(); body.append('foto', file); const { data } = await api.post('/upload', body, { headers: { 'Content-Type': 'multipart/form-data' } }); set('foto_url', data.url); } catch (err) { setError(err.response?.data?.message || 'Gagal mengunggah foto.'); } finally { setUploading(false); } };
  const save = async (event) => { event.preventDefault(); setSaving(true); setError(''); setMessage(''); try { const { data } = await api.put('/auth/profile', form); updateUser(data.user); setMessage(data.message); } catch (err) { setError(err.response?.data?.message || 'Gagal menyimpan profil.'); } finally { setSaving(false); } };
  return <DashboardLayout title="Profil Saya" subtitle="Kelola informasi akun dan tampilan profil Anda."><form onSubmit={save} className="max-w-2xl rounded-2xl border border-slate-200 bg-white p-6 shadow-card"><div className="mb-6 flex items-center gap-5">{form.foto_url ? <img src={form.foto_url} alt="Foto profil" className="h-20 w-20 rounded-full border border-slate-200 object-cover" /> : <div className="flex h-20 w-20 items-center justify-center rounded-full bg-brand/10 text-2xl font-bold text-brand">{form.nama.slice(0, 1).toUpperCase()}</div>}<label className="inline-flex cursor-pointer items-center gap-2 rounded-xl border border-slate-300 px-3 py-2 text-sm text-slate-600 hover:bg-slate-50"><Camera size={16} />{uploading ? 'Mengunggah…' : 'Ubah foto'}<input className="hidden" type="file" accept="image/jpeg,image/png,image/webp" onChange={upload} /></label></div>{error && <p role="alert" className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{message && <p className="mb-4 rounded-xl bg-green-50 p-3 text-sm text-green-700">{message}</p>}<div className="grid gap-4 sm:grid-cols-2"><Field label="Nama" value={form.nama} onChange={(value) => set('nama', value)} required /><Field label="Username" value={form.username} onChange={(value) => set('username', value)} required /><Field label="Email" type="email" value={form.email} onChange={(value) => set('email', value)} /></div><label className="mt-4 block text-sm font-medium text-slate-700">Deskripsi<textarea value={form.deskripsi} onChange={(event) => set('deskripsi', event.target.value)} rows="4" className="mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm font-normal" placeholder="Tulis deskripsi singkat tentang peran atau profil Anda." /></label><div className="mt-5"><Button disabled={saving || uploading} type="submit">{saving && <Loader2 size={16} className="animate-spin" />}{saving ? 'Menyimpan…' : 'Simpan Profil'}</Button></div></form></DashboardLayout>;
}
function Field({ label, type = 'text', value, onChange, required }) { return <label className="block text-sm font-medium text-slate-700">{label}<input type={type} required={required} value={value} onChange={(event) => onChange(event.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm font-normal" /></label>; }
